version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: oauth2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/oauth2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwe123
